name: Simple Test Action

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "* * * * *"    # â° Trigger every minute (UTC)
  workflow_dispatch:       # ğŸ–± Optional: Manual trigger from UI
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "ğŸ‘‹ Hello from GitHub Actions!"

      - name: Run dummy script
        run: |
          echo "This is a dummy step"
          echo "You can replace this with your actual logic"

